In [ ]:
import numpy as np

In [ ]:
temps = np.array([30, 32, 35, 28])
print(temps + 1)

[31 33 36 29]


In [ ]:
list1 = [1, 2, 3]
array1 = np.array([1, 2, 3])

# Multiply each by 2
list_result = [x * 2 for x in list1]
array_result = array1 * 2

print("List:", list_result)
print("array1:", array_result)

List: [2, 4, 6]
array1: [2 4 6]


In [ ]:
# 1D array
marks_1d = np.array([85, 90, 78])
print("1D:", marks_1d)

# 2D array
marks_2d = np.array([[85, 90, 78], [88, 92, 80]])
print("2D:\n", marks_2d)

# 3D array
marks_3d = np.array([[[85, 90], [78, 88]], [[92, 80], [70, 60]]])
print("3D:\n", marks_3d)

1D: [85 90 78]
2D:
 [[85 90 78]
 [88 92 80]]
3D:
 [[[85 90]
  [78 88]]

 [[92 80]
  [70 60]]]


In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
arr = np.array([1.5, 2.7, 3.1])
print(arr.dtype)

float64


In [ ]:
a = np.array([[1, 2, 3, 4], [4, 5, 6, 8]])
print("Shape:", a.shape)
print("Size:", a.size)

Shape: (2, 4)
Size: 8


In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr[0])
arr[2] = 99
print(arr)

# 2D array
arr_2d = np.array([[5, 10], [15, 20]])
print(arr_2d[1, 0])

# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d[1, 0, 1])

10
[10 20 99 40]
15
6


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:5])
print(arr[::2])
print(arr[::-1])

matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(matrix[0:2, 1:3])

[20 30 40 50]
[10 30 50]
[60 50 40 30 20 10]
[[2 3]
 [5 6]]


In [ ]:
scores = np.array([45, 78, 89, 90, 67])
print(scores[scores > 80])

[89 90]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
indice = [0, 2, 4]
print(arr[indice])

[10 30 50]


In [ ]:
store1 = np.array([100, 150, 200])
store2 = np.array([90, 160, 210])

# Element-wise operations
print("Add:", store1 + store2)
print("Subtract:", store1 - store2)
print("Multiply:", store1 * store2)
print("Divide:", store1 / store2)

Add: [190 310 410]
Subtract: [ 10 -10 -10]
Multiply: [ 9000 24000 42000]
Divide: [1.11111111 0.9375     0.95238095]


In [ ]:
marks = np.array([60, 70, 80])
print(marks + 5)
print(marks * 2)

[65 75 85]
[120 140 160]


In [ ]:
scores = np.array([45, 67, 88, 39])
print(scores[scores >= 50])

[67 88]


In [ ]:
scores = np.array([45, 67, 88, 39])
print((scores >= 50) & (scores > 70))
print((scores >= 50) | (scores > 70))
print(~(scores >= 50) | (scores > 70))

[False False  True False]
[False  True  True False]
[ True False  True  True]


In [ ]:
marks = np.array([80, 90, 70, 60])
print("Total:", marks.sum())
print("Average:", marks.mean())
print("Min:", marks.min())
print("Max:", marks.max())

Total: 300
Average: 75.0
Min: 60
Max: 90


In [ ]:
marks = np.array([[80, 90, 70],
[60, 85, 75]])
print(marks.sum(axis=0))
print(marks.sum(axis=1))

[140 175 145]
[240 220]


In [ ]:
marks = np.array([[50, 60, 70],
[80, 90, 100]])
bonus = 10
# Broadcasting adds 10 to every element
print(marks + bonus)

grades = np.array([[85, 90, 95],
[80, 85, 90]])
curve = np.array([1, 2, 3])
print(grades + curve)

[[ 60  70  80]
 [ 90 100 110]]
[[86 92 98]
 [81 87 93]]


In [ ]:
marks = np.array([[50, 60, 70],
[80, 90, 100]])
reshaped = marks.reshape(3,2)
print("Reshaped:\n", reshaped)

Reshaped:
 [[ 50  60]
 [ 70  80]
 [ 90 100]]


In [ ]:
matrix = np.array([[1, 2, 3],
[4, 5, 6]])
flat = matrix.flatten()
print(flat)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.size)
resized = np.resize(arr, (2, 3))
print(resized)
print(resized.size)

4
[[1 2 3]
 [4 1 2]]
6


In [ ]:
matrix = np.array([[1, 2],
[3, 4],
[5, 6]])
print("Original:\n", matrix)
print("Transposed:\n", matrix.T)

Original:
 [[1 2]
 [3 4]
 [5 6]]
Transposed:
 [[1 3 5]
 [2 4 6]]


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
print("Vertical:\n", np.vstack((a, b)))
print("Horizontal:\n", np.hstack((a, b)))

Vertical:
 [[1 2]
 [3 4]]
Horizontal:
 [1 2 3 4]


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
split_arr = np.split(arr, 3) # Split into 3 equal parts
print(split_arr)
print([split_arr[0], split_arr[2]])
print(split_arr[1][0])


[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20]), array([50, 60])]
30


In [ ]:
matrix = np.array([[1, 2, 3, 4],
[5, 6, 7, 8]])
# Split columns
left, right = np.hsplit(matrix, 2)
print("Left:\n", left)
print("Right:\n", right)

Left:
 [[1 2]
 [5 6]]
Right:
 [[3 4]
 [7 8]]


In [ ]:
# Split rows
top, bottom = np.vsplit(matrix, 2)
print("Top:\n", top)
print("Bottom:\n", bottom)

Top:
 [[1 2 3 4]]
Bottom:
 [[5 6 7 8]]


In [ ]:
arr = np.array([10, 20, 30, 40])
view = arr[1:3]
view[0] = 99

print("View:", view) # [99 30]
print("Original:", arr) # [10 99 30 40] ← changed!

View: [99 30]
Original: [10 99 30 40]


In [ ]:
arr = np.array([1, 2, 3, 4])
copy_arr = arr.copy()
copy_arr[0] = 99

print("Copy:", copy_arr) # [99 2 3 4]
print("Original:", arr) # [1 2 3 4] ← unchanged

Copy: [99  2  3  4]
Original: [1 2 3 4]


In [ ]:
fruits = np.array(['apple', 'banana', 'cherry'])
for fruit in fruits:
  print(fruit)

apple
banana
cherry


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
for row in arr:
  print("Row:", row)

Row: [1 2]
Row: [3 4]
Row: [5 6]


In [ ]:
arr = np.array([[1, 2], [3, 4]])
for val in arr.flat:
  print(val, end = " ")

1 2 3 4 

In [ ]:
arr = np.array([1, 2, 3])
for x in np.nditer(arr, op_flags=['readwrite']):
  x[...] = x * 2

print("Modified:", arr)

Modified: [2 4 6]


In [ ]:
arr = np.array([[100, 200], [300, 400]])
for index, value in np.ndenumerate(arr):
  print(f"Index {index} has value {value}")

Index (0, 0) has value 100
Index (0, 1) has value 200
Index (1, 0) has value 300
Index (1, 1) has value 400


In [ ]:
print(np.random.rand(3))

[0.51497476 0.20918595 0.91865971]


In [ ]:
print(np.random.rand(2, 2))

[[0.82736872 0.43281379]
 [0.60160681 0.99426764]]


In [ ]:
print(np.random.randint(10, 20, size=5))

[14 15 17 14 15]


In [ ]:
print(np.random.randn(4))
print(np.random.randn(2, 3))

[-0.90440924 -1.29097463 -0.91564395 -0.46750017]
[[-0.21931697 -1.0542615   1.01354392]
 [ 0.23234156  0.87306347 -0.60068308]]


In [ ]:
items = ['apple', 'banana', 'cherry']
print(np.random.choice(items, size=2))

['apple' 'cherry']


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("Shuffled:", arr)

Shuffled: [1 4 2 3 5]


In [ ]:
arr = np.array([10, 20, 30, 40])
shuffled = np.random.permutation(arr)
print("Original:", arr)
print("Shuffled Copy:", shuffled)

Original: [10 20 30 40]
Shuffled Copy: [30 10 20 40]


In [ ]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


In [ ]:
names = np.array(['Alice', 'BOB', 'ChArLiE'])
print(np.char.lower(names))
print(np.char.upper(names))

arr = np.array(['hello', 'world'])
print(np.char.capitalize(arr))

first = np.array(['John', 'Jane'])
last = np.array(['Doe', 'Smith'])
print(np.char.add(first,last))

words = np.array(['Hi', 'Bye'])
print(np.char.multiply(words, 3))

arr = np.array(['Hi', 'Hello'])
print(np.char.center(arr, 10, fillchar='*'))

sentences = np.array(['Hello World', 'Python NumPy'])
print(np.char.split(sentences))

arr = np.array([' apple ', ' banana'])
print(np.char.strip(arr))

arr = np.array(['I hate bugs', 'Bugs are bad'])
print(np.char.replace(arr, 'bugs', 'features'))

emails = np.array(['user@example.com', 'admin@site.org'])
print(np.char.find(emails, '@'))

['alice' 'bob' 'charlie']
['ALICE' 'BOB' 'CHARLIE']
['Hello' 'World']
['JohnDoe' 'JaneSmith']
['HiHiHi' 'ByeByeBye']
['****Hi****' '**Hello***']
[list(['Hello', 'World']) list(['Python', 'NumPy'])]
['apple' 'banana']
['I hate features' 'Bugs are bad']
[4 5]


In [ ]:
# Array with NaN (missing) values
data = np.array([1, 2, np.nan, 4, 5, np.nan])
print(data)

[ 1.  2. nan  4.  5. nan]


In [ ]:
# Check for NaN values
is_nan = np.isnan(data)
print("Check for NaN values:", is_nan)

Check for NaN values: [False False  True False False  True]


In [ ]:
# Replace NaN values with 0
cleaned_data = np.nan_to_num(data, nan=0)
print("Data After Replacing NaN with 0:", cleaned_data)

Data After Replacing NaN with 0: [1. 2. 0. 4. 5. 0.]


In [ ]:
# Replace NaN values with the mean of the array
mean_value = np.nanmean(data)
filled_data = np.where(np.isnan(data), mean_value, data)
print("Data After Filling NaN with Mean:", filled_data)

Data After Filling NaN with Mean: [1. 2. 3. 4. 5. 3.]


In [ ]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np

rand_nums = np.random.rand(5)
print(rand_nums)

[0.59865848 0.15601864 0.15599452 0.05808361 0.86617615]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)

print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr = np.array([10, 20, 5, 40, 15])

print("Maximum:", arr.max())
print("Minimum:", arr.min())

Maximum: 40
Minimum: 5


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b

print(result)

[5 7 9]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std Dev:", np.std(arr))

Mean: 3.0
Median: 3.0
Std Dev: 1.4142135623730951


In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dot(a, b)

print(result)

[[19 22]
 [43 50]]


In [ ]:
import numpy as np

arr = np.arange(2, 21, 2)

print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

reversed_arr = arr[::-1]

print(reversed_arr)

[5 4 3 2 1]


In [ ]:
import numpy as np

arr = np.array([1, 6, 3, 8, 2, 9])

indices = np.where(arr > 5)

print(indices)

(array([1, 3, 5]),)


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked = np.vstack((a, b))

print(stacked)

[[1 2 3]
 [4 5 6]]
